# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'math_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MathProblemGenerator(object):
    def setupUi(self, MathProblemGenerator):
        MathProblemGenerator.setObjectName("MathProblemGenerator")
        MathProblemGenerator.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MathProblemGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rangeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.rangeInput.setObjectName("rangeInput")
        self.horizontalLayout.addWidget(self.rangeInput)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.problemCountInput = QtWidgets.QLineEdit(self.centralwidget)
        self.problemCountInput.setObjectName("problemCountInput")
        self.horizontalLayout.addWidget(self.problemCountInput)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.mixedCountInput = QtWidgets.QLineEdit(self.centralwidget)
        self.mixedCountInput.setObjectName("mixedCountInput")
        self.horizontalLayout.addWidget(self.mixedCountInput)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout.addWidget(self.generateButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.problemsText = QtWidgets.QTextEdit(self.centralwidget)
        self.problemsText.setReadOnly(True)
        self.problemsText.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.problemsText.setObjectName("problemsText")
        self.verticalLayout.addWidget(self.problemsText)
        MathProblemGenerator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MathProblemGenerator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MathProblemGenerator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MathProblemGenerator)
        self.statusbar.setObjectName("statusbar")
        MathProblemGenerator.setStatusBar(self.statusbar)

        self.retranslateUi(MathProblemGenerator)
        self.generateButton.clicked.connect(MathProblemGenerator.generate_problems) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MathProblemGenerator)

    def retranslateUi(self, MathProblemGenerator):
        _translate = QtCore.QCoreApplication.translate
        MathProblemGenerator.setWindowTitle(_translate("MathProblemGenerator", "小学数学题生成器"))
        self.label.setText(_translate("MathProblemGenerator", "请输入数字范围（1-1000）:"))
        self.rangeInput.setText(_translate("MathProblemGenerator", "100"))
        self.label_2.setText(_translate("MathProblemGenerator", "题目数量:"))
        self.problemCountInput.setText(_translate("MathProblemGenerator", "20"))
        self.label_3.setText(_translate("MathProblemGenerator", "混合题目数量:"))
        self.mixedCountInput.setText(_translate("MathProblemGenerator", "5"))
        self.generateButton.setText(_translate("MathProblemGenerator", "生成题目"))
        self.problemsText.setPlaceholderText(_translate("MathProblemGenerator", "生成的题目将显示在这里..."))
